/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RankingsRouteImport } from './routes/rankings'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MuseumsIndexRouteImport } from './routes/museums/index'
import { Route as MuseumsSlugRouteImport } from './routes/museums/$slug'

const RankingsRoute = RankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MuseumsIndexRoute = MuseumsIndexRouteImport.update({
  id: '/museums/',
  path: '/museums/',
  getParentRoute: () => rootRouteImport,
} as any)
const MuseumsSlugRoute = MuseumsSlugRouteImport.update({
  id: '/museums/$slug',
  path: '/museums/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/rankings': typeof RankingsRoute
  '/museums/$slug': typeof MuseumsSlugRoute
  '/museums/': typeof MuseumsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/rankings': typeof RankingsRoute
  '/museums/$slug': typeof MuseumsSlugRoute
  '/museums': typeof MuseumsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/rankings': typeof RankingsRoute
  '/museums/$slug': typeof MuseumsSlugRoute
  '/museums/': typeof MuseumsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/rankings' | '/museums/$slug' | '/museums/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/rankings' | '/museums/$slug' | '/museums'
  id: '__root__' | '/' | '/about' | '/rankings' | '/museums/$slug' | '/museums/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  RankingsRoute: typeof RankingsRoute
  MuseumsSlugRoute: typeof MuseumsSlugRoute
  MuseumsIndexRoute: typeof MuseumsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rankings': {
      id: '/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/museums/': {
      id: '/museums/'
      path: '/museums'
      fullPath: '/museums/'
      preLoaderRoute: typeof MuseumsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/museums/$slug': {
      id: '/museums/$slug'
      path: '/museums/$slug'
      fullPath: '/museums/$slug'
      preLoaderRoute: typeof MuseumsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  RankingsRoute: RankingsRoute,
  MuseumsSlugRoute: MuseumsSlugRoute,
  MuseumsIndexRoute: MuseumsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
